version: '3.8'

services:
  web:
    build:
      context: . # Assumes Dockerfile is in the current directory
      dockerfile: Dockerfile
    ports:
      - "6030:6030" # Maps host port 6020 to container port 6020.
    environment:
      - FLASK_APP=run.py
      - FLASK_CONFIG=production
      
